Config.FarmHerbs = {
	["seed_hop"] = {--Item Seed ID
		enableHerbToSeed = false,--If you have enabeld after you use herb -> automaticaly get seeds
		multipleUse = false,--If you have enabled you can use herb and get input with "To seed" "Interact"
		multipleEvent = "gum_farming:useSeed",--argument is herbSeed, herbName, herbCount (multipleUse)
		herbToSeed = 3,--How much get from herb seeds
		herbName = "Hop",--Herb name
		herbItem = "crop_hop",--Herb item

		itIsTree = false,--Regrow system. Plant stay there but you can pick herb, and after again grow you an pick again. Good for apple trees etc.
		canPickAfterGrow = 0,--How much times from regrow system you can pick herb

		-- coordsLocks = {--If you want lock coords for plant herb
		-- 	[1] = {1397.2660, 210.4541, 91.6371, 20.00},
		-- 	[2] = {1410.5343, 224.5811, 90.9479, 20.00},
		-- 	[3] = {1387.0291, 235.8169, 91.3079, 20.00},
		-- 	[4] = {1373.8512, 224.7362, 90.9936, 20.00}
		-- },
		potStageProps = {--Stage is calculated automaticaly from grow time
			-- *STAGE   |   MODEL     |    TIME | HOW MUCH IN GROUND*(Z Value) --
			[1] = {"s_inv_milkweed01bx", 3, 0.0},--Must be +1 from grow time
			[2] = {"s_inv_milkweed01cx", 2, 0.0},
			[3] = {"s_inv_milkweed01x", 2, 0.0},
			[4] = {"s_milkweed01x", 1, 0.0},
		},
		weatherAffect = true,--If is rain -> automaticaly water herb
		growTime = 30,--300 min time without affecting temp
		temperatureSlow = -3,--If temperature is under -3 automaticaly slow grow
		temperatureGood = {-3, 30},--If temperature between this, herb grow normal
		temperatureHot = 30,--If temperature is bigger thjan 30 herb need more water (2x more)

		fertilizer = 0,--If you plant herb, how much have fertilize
		quality = 100,--If you plant herb, how much have quality
		procure = 100,--If you plant herb, how much have procure
		jerks = 0,--If you plant herb, how much have jerks

		gatherAnimation = {"mech_pickup@plant@yarrow","base", 3},--Animation for gather herb
		rewardItem = {--If you have disabled quality set [XX] to [0]
			[80] = {"crop_hop", 5},--Upper 80% to 100%
			[50] = {"crop_hop", 3},--Upper 50% to 80%
			[25] = {"crop_hop", 2},--Upper 25% to 50%
			[0] = {"crop_hop", 1},--Upper 0% to 25%
		},
	},

	["seed_carrot"] = {
		enableHerbToSeed = false,
		multipleUse = false,
		multipleEvent = "gum_farming:useSeed",
		herbToSeed = 3,
		herbName = "Carrot",
		herbItem = "crop_carrot",
		itIsTree = false,
		canPickAfterGrow = 0,
		potStageProps = {
			[1] = {"s_inv_wildcarrot01x", 6, 0.8},
			[2] = {"s_inv_wildcarrot01x", 3, 0.6},
			[3] = {"s_inv_wildcarrot01x", 2, 0.3},
			[4] = {"s_inv_wildcarrot01x", 1, 0.0},
		},
		weatherAffect = true,
		growTime = 30,
		temperatureSlow = -3,
		temperatureGood = {-3, 30},
		temperatureHot = 30,
		gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 4},

		fertilizer = 0,
		quality = 100,
		procure = 100,
		jerks = 0,

		rewardItem = {
			[80] = {"crop_carrot", 5},
			[50] = {"crop_carrot", 3},
			[25] = {"crop_carrot", 2},
			[0] = {"crop_carrot", 1},
		},
	},

	["seed_apple"] = {
		enableHerbToSeed = false,
		multipleUse = false,
		multipleEvent = "gum_farming:useSeed",
		herbToSeed = 3,
		herbName = "Apple",
		herbItem = "crop_apple",
		itIsTree = true,
		canPickAfterGrow = 10,
		potStageProps = {
			[1] = {"p_tree_apple_01", 6, 3.0},
			[2] = {"p_tree_apple_01", 3, 2.2},
			[3] = {"p_tree_apple_01", 2, 1.4},
			[4] = {"p_tree_apple_01", 1, 0.8},
		},
		weatherAffect = true,
		growTime = 30,
		temperatureSlow = -3,
		temperatureGood = {-3, 30},
		temperatureHot = 30,

		fertilizer = 0,
		quality = 100,
		procure = 100,
		jerks = 0,

		gatherAnimation = {"mech_pickup@plant@orchid_tree","base", 5},
		rewardItem = {
			[80] = {"crop_apple", 5},
			[50] = {"crop_apple", 3},
			[25] = {"crop_apple", 2},
			[0] = {"crop_apple", 1},
		},
	},

	["seed_wheat"] = {
		enableHerbToSeed = false,
		multipleUse = false,
		multipleEvent = "gum_farming:useSeed",
		herbToSeed = 3,
		herbName = "Wheat",
		herbItem = "crop_wheat",
		itIsTree = false,
		canPickAfterGrow = 0,
		potStageProps = {
			[1] = {"crp_wheat_dry_long_aa_sim", 6, 3.0},
			[2] = {"crp_wheat_dry_long_aa_sim", 3, 2.2},
			[3] = {"crp_wheat_dry_long_aa_sim", 2, 1.4},
			[4] = {"crp_wheat_dry_long_aa_sim", 1, 0.8},
		},
		weatherAffect = true,
		growTime = 30,
		temperatureSlow = -3,
		temperatureGood = {-3, 30},
		temperatureHot = 30,

		fertilizer = 0,
		quality = 100,
		procure = 100,
		jerks = 0,

		gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
		rewardItem = {
			[80] = {"crop_wheat", 5},
			[50] = {"crop_wheat", 3},
			[25] = {"crop_wheat", 2},
			[0] = {"crop_wheat", 1},
		},
	},
	
		["seed_corn"] = {
		enableHerbToSeed = false,
		multipleUse = false,
		multipleEvent = "gum_farming:useSeed",
		herbToSeed = 3,
		herbName = "Corn",
		herbItem = "crop_corn",
		itIsTree = false,
		canPickAfterGrow = 0,
		potStageProps = {
			[1] = {"crp_cornstalks_ab_sim", 6, 3.0},
			[2] = {"crp_cornstalks_ab_sim", 3, 2.2},
			[3] = {"crp_cornstalks_ab_sim", 2, 1.4},
			[4] = {"crp_cornstalks_ab_sim", 1, 0.8},
		},
		weatherAffect = true,
		growTime = 30,
		temperatureSlow = -3,
		temperatureGood = {-3, 30},
		temperatureHot = 30,

		fertilizer = 0,
		quality = 100,
		procure = 100,
		jerks = 0,

		gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
		rewardItem = {
			[80] = {"crop_corn", 5},
			[50] = {"crop_corn", 3},
			[25] = {"crop_corn", 2},
			[0] = {"crop_corn", 1},
		},
	},
	
			["seed_potato"] = {
		enableHerbToSeed = false,
		multipleUse = false,
		multipleEvent = "gum_farming:useSeed",
		herbToSeed = 3,
		herbName = "Potato",
		herbItem = "crop_potato",
		itIsTree = false,
		canPickAfterGrow = 0,
		potStageProps = {
			[1] = {"crp_potato_aa_sim", 6, 3.0},
			[2] = {"crp_potato_aa_sim", 3, 2.2},
			[3] = {"crp_potato_aa_sim", 2, 1.4},
			[4] = {"crp_potato_aa_sim", 1, 0.8},
		},
		weatherAffect = true,
		growTime = 30,
		temperatureSlow = -3,
		temperatureGood = {-3, 30},
		temperatureHot = 30,

		fertilizer = 0,
		quality = 100,
		procure = 100,
		jerks = 0,

		gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
		rewardItem = {
			[80] = {"crop_potato", 5},
			[50] = {"crop_potato", 3},
			[25] = {"crop_potato", 2},
			[0] = {"crop_potato", 1},
		},
	},
		
			["seed_pumpkin"] = {
		enableHerbToSeed = false,
		multipleUse = false,
		multipleEvent = "gum_farming:useSeed",
		herbToSeed = 3,
		herbName = "Pumpkin",
		herbItem = "crop_pumpkin",
		itIsTree = false,
		canPickAfterGrow = 0,
		potStageProps = {
			[1] = {"crp_berry_sap_aa_sim", 6, 3.0},
			[2] = {"crp_berry_sap_aa_sim", 3, 2.2},
			[3] = {"crp_berry_sap_aa_sim", 2, 1.4},
			[4] = {"crp_berry_sap_aa_sim", 1, 0.8},
		},
		weatherAffect = true,
		growTime = 30,
		temperatureSlow = -3,
		temperatureGood = {-3, 30},
		temperatureHot = 30,

		fertilizer = 0,
		quality = 100,
		procure = 100,
		jerks = 0,

		gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
		rewardItem = {
			[80] = {"crop_pumpkin", 5},
			[50] = {"crop_pumpkin", 3},
			[25] = {"crop_pumpkin", 2},
			[0] = {"crop_pumpkin", 1},
		},
	},
			
			["seed_lettuce"] = {
		enableHerbToSeed = false,
		multipleUse = false,
		multipleEvent = "gum_farming:useSeed",
		herbToSeed = 3,
		herbName = "Lettuce",
		herbItem = "crop_lettuce",
		itIsTree = false,
		canPickAfterGrow = 0,
		potStageProps = {
			[1] = {"crp_lettuce_aa_sim", 6, 3.0},
			[2] = {"crp_lettuce_aa_sim", 3, 2.2},
			[3] = {"crp_lettuce_aa_sim", 2, 1.4},
			[4] = {"crp_lettuce_aa_sim", 1, 0.8},
		},
		weatherAffect = true,
		growTime = 30,
		temperatureSlow = -3,
		temperatureGood = {-3, 30},
		temperatureHot = 30,

		fertilizer = 0,
		quality = 100,
		procure = 100,
		jerks = 0,

		gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
		rewardItem = {
			[80] = {"crop_lettuce", 5},
			[50] = {"crop_lettuce", 3},
			[25] = {"crop_lettuce", 2},
			[0] = {"crop_lettuce", 1},
		},
	},
			
			["seed_orange"] = {
		enableHerbToSeed = false,
		multipleUse = false,
		multipleEvent = "gum_farming:useSeed",
		herbToSeed = 3,
		herbName = "Orange",
		herbItem = "seed_orange",
		itIsTree = true,
		canPickAfterGrow = 0,
		potStageProps = {
			[1] = {"p_tree_orange_01", 6, 3.0},
			[2] = {"p_tree_orange_01", 3, 2.2},
			[3] = {"p_tree_orange_01", 2, 1.4},
			[4] = {"p_tree_orange_01", 1, 0.8},
		},
		weatherAffect = true,
		growTime = 30,
		temperatureSlow = -3,
		temperatureGood = {-3, 30},
		temperatureHot = 30,

		fertilizer = 0,
		quality = 100,
		procure = 100,
		jerks = 0,

		gatherAnimation = {"mech_pickup@plant@orchid_tree","base", 5},
		rewardItem = {
			[80] = {"crop_orange", 5},
			[50] = {"crop_orange", 3},
			[25] = {"crop_orange", 2},
			[0] = {"crop_orange", 1},
		},
	},
			
			["seed_grape"] = {
		enableHerbToSeed = false,
		multipleUse = false,
		multipleEvent = "gum_farming:useSeed",
		herbToSeed = 3,
		herbName = "Grape",
		herbItem = "seed_grape",
		itIsTree = false,
		canPickAfterGrow = 0,
		potStageProps = {
			[1] = {"rdr2_tree_rata01", 6, 3.0},
			[2] = {"rdr2_tree_rata01", 3, 2.2},
			[3] = {"rdr2_tree_rata01", 2, 1.4},
			[4] = {"rdr2_tree_rata01", 1, 0.8},
		},
		weatherAffect = true,
		growTime = 30,
		temperatureSlow = -3,
		temperatureGood = {-3, 30},
		temperatureHot = 30,

		fertilizer = 0,
		quality = 100,
		procure = 100,
		jerks = 0,

		gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
		rewardItem = {
			[80] = {"crop_grape", 5},
			[50] = {"crop_grape", 3},
			[25] = {"crop_grape", 2},
			[0] = {"crop_grape", 1},
		},
	},
				
			["seed_onion"] = {
		enableHerbToSeed = false,
		multipleUse = false,
		multipleEvent = "gum_farming:useSeed",
		herbToSeed = 3,
		herbName = "Onion",
		herbItem = "seed_onion",
		itIsTree = false,
		canPickAfterGrow = 0,
		potStageProps = {
			[1] = {"crp_wheat_sap_long_aa_sim", 6, 3.0},
			[2] = {"crp_wheat_sap_long_aa_sim", 3, 2.2},
			[3] = {"crp_wheat_sap_long_aa_sim", 2, 1.4},
			[4] = {"crp_wheat_sap_long_aa_sim", 1, 0.8},
		},
		weatherAffect = true,
		growTime = 30,
		temperatureSlow = -3,
		temperatureGood = {-3, 30},
		temperatureHot = 30,

		fertilizer = 0,
		quality = 100,
		procure = 100,
		jerks = 0,

		gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
		rewardItem = {
			[80] = {"crop_onion", 5},
			[50] = {"crop_onion", 3},
			[25] = {"crop_onion", 2},
			[0] = {"crop_onion", 1},
		},
	},
				
			["seed_cherry"] = {
		enableHerbToSeed = false,
		multipleUse = false,
		multipleEvent = "gum_farming:useSeed",
		herbToSeed = 3,
		herbName = "Cherry",
		herbItem = "seed_cherry",
		itIsTree = false,
		canPickAfterGrow = 0,
		potStageProps = {
			[1] = {"rdr_bush_decor_aa", 301, 6.0},
			[2] = {"rdr_bush_decor_aa", 250, 2.2},
			[3] = {"rdr_bush_decor_aa", 100, 1.4},
			[4] = {"rdr_bush_decor_aa", 1, 0.8},
		},
		weatherAffect = true,
		growTime = 30,
		temperatureSlow = -3,
		temperatureGood = {-3, 30},
		temperatureHot = 30,

		fertilizer = 0,
		quality = 100,
		procure = 100,
		jerks = 0,

		gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
		rewardItem = {
			[80] = {"crop_cherry", 5},
			[50] = {"crop_cherry", 3},
			[25] = {"crop_cherry", 2},
			[0] = {"crop_cherry", 1},
		},
	},
					
			["seed_tomato"] = {
		enableHerbToSeed = false,
		multipleUse = false,
		multipleEvent = "gum_farming:useSeed",
		herbToSeed = 3,
		herbName = "Tomato",
		herbItem = "seed_tomato",
		itIsTree = false,
		canPickAfterGrow = 0,
		potStageProps = {
			[1] = {"crp_tomatoes_aa_sim", 6, 3.0},
			[2] = {"crp_tomatoes_aa_sim", 3, 2.2},
			[3] = {"crp_tomatoes_aa_sim", 2, 1.4},
			[4] = {"crp_tomatoes_aa_sim", 1, 0.8},
		},
		weatherAffect = true,
		growTime = 30,
		temperatureSlow = -3,
		temperatureGood = {-3, 30},
		temperatureHot = 30,

		fertilizer = 0,
		quality = 100,
		procure = 100,
		jerks = 0,

		gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
		rewardItem = {
			[80] = {"crop_tomato", 5},
			[50] = {"crop_tomato", 3},
			[25] = {"crop_tomato", 2},
			[0] = {"crop_tomato", 1},
		},
	},
	
				["seed_sugarcane"] = {
		enableHerbToSeed = false,
		multipleUse = false,
		multipleEvent = "gum_farming:useSeed",
		herbToSeed = 3,
		herbName = "Sugarcane",
		herbItem = "seed_sugarcane",
		itIsTree = false,
		canPickAfterGrow = 0,
		potStageProps = {
			[1] = {"crp_sugarcane_ac_sim", 6, 3.0},
			[2] = {"crp_sugarcane_ac_sim", 3, 2.2},
			[3] = {"crp_sugarcane_ac_sim", 2, 1.4},
			[4] = {"crp_sugarcane_ac_sim", 1, 0.8},
		},
		weatherAffect = true,
		growTime = 30,
		temperatureSlow = -3,
		temperatureGood = {-3, 30},
		temperatureHot = 30,

		fertilizer = 0,
		quality = 100,
		procure = 100,
		jerks = 0,

		gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
		rewardItem = {
			[80] = {"crop_sugarcane", 5},
			[50] = {"crop_sugarcane", 3},
			[25] = {"crop_sugarcane", 2},
			[0] = {"crop_sugarcane", 1},
		},
	},
		
				["seed_indian_tobacco"] = {
		enableHerbToSeed = false,
		multipleUse = false,
		multipleEvent = "gum_farming:useSeed",
		herbToSeed = 3,
		herbName = "Indian Tobacco",
		herbItem = "seed_indian_tobacco",
		itIsTree = false,
		canPickAfterGrow = 0,
		potStageProps = {
			[1] = {"crp_tobaccoplant_bc_sim", 6, 3.0},
			[2] = {"crp_tobaccoplant_bc_sim", 3, 2.2},
			[3] = {"crp_tobaccoplant_bc_sim", 2, 1.4},
			[4] = {"crp_tobaccoplant_bc_sim", 1, 0.8},
		},
		weatherAffect = true,
		growTime = 30,
		temperatureSlow = -3,
		temperatureGood = {-3, 30},
		temperatureHot = 30,

		fertilizer = 0,
		quality = 100,
		procure = 100,
		jerks = 0,

		gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
		rewardItem = {
			[80] = {"crop_tobacco", 5},
			[50] = {"crop_tobacco", 3},
			[25] = {"crop_tobacco", 2},
			[0] = {"crop_tobacco", 1},
		},
	},
	
        ["seed_agarita"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Agarita",
                herbItem = "crop_agarita",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"mp005_s_inv_agarita_01x", 6, 3.0},
                        [2] = {"mp005_s_inv_agarita_01x", 3, 2.2},
                        [3] = {"mp005_s_inv_agarita_01x", 2, 1.4},
                        [4] = {"mp005_s_inv_agarita_01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_agarita", 5},
                        [50] = {"crop_agarita", 3},
                        [25] = {"crop_agarita", 2},
                        [0] = {"crop_agarita", 1},
                },
        },
	
        ["seed_bitterweed"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Bitterweed",
                herbItem = "crop_bitterweed",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"mp005_s_inv_bitterweed01x", 6, 3.0},
                        [2] = {"mp005_s_inv_bitterweed01x", 3, 2.2},
                        [3] = {"mp005_s_inv_bitterweed01x", 2, 1.4},
                        [4] = {"mp005_s_inv_bitterweed01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_bitterweed", 5},
                        [50] = {"crop_bitterweed", 3},
                        [25] = {"crop_bitterweed", 2},
                        [0] = {"crop_bitterweed", 1},
                },
        },
	
        ["seed_blood_flower"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Blood Flower",
                herbItem = "crop_blood_flower",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"mp005_s_inv_bloodflw01x", 6, 3.0},
                        [2] = {"mp005_s_inv_bloodflw01x", 3, 2.2},
                        [3] = {"mp005_s_inv_bloodflw01x", 2, 1.4},
                        [4] = {"mp005_s_inv_bloodflw01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_blood_flower", 5},
                        [50] = {"crop_blood_flower", 3},
                        [25] = {"crop_blood_flower", 2},
                        [0] = {"crop_blood_flower", 1},
                },
        },
	
        ["seed_cardinal_flower"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Cardinal Flower",
                herbItem = "crop_cardinal_flower",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"mp005_s_inv_cardinal01x", 6, 3.0},
                        [2] = {"mp005_s_inv_cardinal01x", 3, 2.2},
                        [3] = {"mp005_s_inv_cardinal01x", 2, 1.4},
                        [4] = {"mp005_s_inv_cardinal01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_cardinal_flower", 5},
                        [50] = {"crop_cardinal_flower", 3},
                        [25] = {"crop_cardinal_flower", 2},
                        [0] = {"crop_cardinal_flower", 1},
                },
        },
	
        ["seed_chocolate_daisy"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Chocolate Daisy",
                herbItem = "crop_chocolate_daisy",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"mp005_s_inv_chocdaisy01x", 6, 3.0},
                        [2] = {"mp005_s_inv_chocdaisy01x", 3, 2.2},
                        [3] = {"mp005_s_inv_chocdaisy01x", 2, 1.4},
                        [4] = {"mp005_s_inv_chocdaisy01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_chocolate_daisy", 5},
                        [50] = {"crop_chocolate_daisy", 3},
                        [25] = {"crop_chocolate_daisy", 2},
                        [0] = {"crop_chocolate_daisy", 1},
                },
        },
	
        ["seed_creek_plum"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Creek Plum",
                herbItem = "crop_creek_plum",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"mp005_s_inv_creekplum01x", 6, 3.0},
                        [2] = {"mp005_s_inv_creekplum01x", 3, 2.2},
                        [3] = {"mp005_s_inv_creekplum01x", 2, 1.4},
                        [4] = {"mp005_s_inv_creekplum01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_creek_plum", 5},
                        [50] = {"crop_creek_plum", 3},
                        [25] = {"crop_creek_plum", 2},
                        [0] = {"crop_creek_plum", 1},
                },
        },
	
        ["seed_texas_bluebonnet"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Texas Bluebonnet",
                herbItem = "crop_texas_bluebonnet",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"mp005_s_inv_texasbon01x", 6, 3.0},
                        [2] = {"mp005_s_inv_texasbon01x", 3, 2.2},
                        [3] = {"mp005_s_inv_texasbon01x", 2, 1.4},
                        [4] = {"mp005_s_inv_texasbon01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_texas_bluebonnet", 5},
                        [50] = {"crop_texas_bluebonnet", 3},
                        [25] = {"crop_texas_bluebonnet", 2},
                        [0] = {"crop_texas_bluebonnet", 1},
                },
        },
	
        ["seed_rhubarb"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Rhubarb",
                herbItem = "crop_rhubarb",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"mp005_s_inv_rhub01x", 6, 3.0},
                        [2] = {"mp005_s_inv_rhub01x", 3, 2.2},
                        [3] = {"mp005_s_inv_rhub01x", 2, 1.4},
                        [4] = {"mp005_s_inv_rhub01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_rhubarb", 5},
                        [50] = {"crop_rhubarb", 3},
                        [25] = {"crop_rhubarb", 2},
                        [0] = {"crop_rhubarb", 1},
                },
        },
	
        ["seed_wisteria"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Wisteria",
                herbItem = "crop_wisteria",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"mp005_s_inv_wisteria01x", 6, 3.0},
                        [2] = {"mp005_s_inv_wisteria01x", 3, 2.2},
                        [3] = {"mp005_s_inv_wisteria01x", 2, 1.4},
                        [4] = {"mp005_s_inv_wisteria01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_wisteria", 5},
                        [50] = {"crop_wisteria", 3},
                        [25] = {"crop_wisteria", 2},
                        [0] = {"crop_rhubarb", 1},
                },
        },
	
        ["seed_alaskan_ginseng"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Alaskan Ginseng",
                herbItem = "crop_alaskan_ginseng",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_alaskanginseng01x", 6, 3.0},
                        [2] = {"s_inv_alaskanginseng01x", 3, 2.2},
                        [3] = {"s_inv_alaskanginseng01x", 2, 1.4},
                        [4] = {"s_inv_alaskanginseng01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_alaskan_ginseng", 5},
                        [50] = {"crop_alaskan_ginseng", 3},
                        [25] = {"crop_alaskan_ginseng", 2},
                        [0] = {"crop_alaskan_ginseng", 1},
                },
        },
	
        ["seed_american_ginseng"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "American Ginseng",
                herbItem = "crop_american_ginseng",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_alaskanginseng01x", 6, 3.0},
                        [2] = {"s_inv_alaskanginseng01x", 3, 2.2},
                        [3] = {"s_inv_alaskanginseng01x", 2, 1.4},
                        [4] = {"s_inv_alaskanginseng01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_american_ginseng", 5},
                        [50] = {"crop_american_ginseng", 3},
                        [25] = {"crop_american_ginseng", 2},
                        [0] = {"crop_american_ginseng", 1},
                },
        },
	
        ["seed_bay_bolete"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Bay Bolete",
                herbItem = "crop_bay_bolete",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_baybolete01bx", 6, 3.0},
                        [2] = {"s_inv_baybolete01bx", 3, 2.2},
                        [3] = {"s_inv_baybolete01bx", 2, 1.4},
                        [4] = {"s_inv_baybolete01bx", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_bay_bolete", 5},
                        [50] = {"crop_bay_bolete", 3},
                        [25] = {"crop_bay_bolete", 2},
                        [0] = {"crop_bay_bolete", 1},
                },
        },
	
        ["seed_blackberry"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Blackberry",
                herbItem = "crop_blackberry",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_blackberry01x", 6, 3.0},
                        [2] = {"s_inv_blackberry01x", 3, 2.2},
                        [3] = {"s_inv_blackberry01x", 2, 1.4},
                        [4] = {"s_inv_blackberry01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_blackberry", 5},
                        [50] = {"crop_blackberry", 3},
                        [25] = {"crop_blackberry", 2},
                        [0] = {"crop_blackberry", 1},
                },
        },
	
        ["seed_black_currant"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Black Currant",
                herbItem = "crop_black_currant",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_blackcurrant01x", 6, 3.0},
                        [2] = {"s_inv_blackcurrant01x", 3, 2.2},
                        [3] = {"s_inv_blackcurrant01x", 2, 1.4},
                        [4] = {"s_inv_blackcurrant01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_black_currant", 5},
                        [50] = {"crop_black_currant", 3},
                        [25] = {"crop_black_currant", 2},
                        [0] = {"crop_black_currant", 1},
                },
        },
	
        ["seed_burdock_root"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Burdock Root",
                herbItem = "crop_burdock_root",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_burdock01x", 6, 3.0},
                        [2] = {"s_inv_burdock01x", 3, 2.2},
                        [3] = {"s_inv_burdock01x", 2, 1.4},
                        [4] = {"s_inv_burdock01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_burdock_root", 5},
                        [50] = {"crop_burdock_root", 3},
                        [25] = {"crop_burdock_root", 2},
                        [0] = {"crop_burdock_root", 1},
                },
        },
	
        ["seed_chanterelles"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Chanterelles",
                herbItem = "crop_chanterelles",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_chanterelles01bx", 6, 3.0},
                        [2] = {"s_inv_chanterelles01bx", 3, 2.2},
                        [3] = {"s_inv_chanterelles01bx", 2, 1.4},
                        [4] = {"s_inv_chanterelles01bx", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_chanterelles", 5},
                        [50] = {"crop_chanterelles", 3},
                        [25] = {"crop_chanterelles", 2},
                        [0] = {"crop_chanterelles", 1},
                },
        },
	
        ["seed_common_bulrush"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Common Bulrush",
                herbItem = "crop_common_bulrush",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_bulrush01x", 6, 3.0},
                        [2] = {"s_inv_bulrush01x", 3, 2.2},
                        [3] = {"s_inv_bulrush01x", 2, 1.4},
                        [4] = {"s_inv_bulrush01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_common_bulrush", 5},
                        [50] = {"crop_common_bulrush", 3},
                        [25] = {"crop_common_bulrush", 2},
                        [0] = {"crop_common_bulrush", 1},
                },
        },
	
        ["seed_creeping_thyme"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Creeping Thyme",
                herbItem = "crop_creeping_thyme",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_thyme01x", 6, 3.0},
                        [2] = {"s_inv_thyme01x", 3, 2.2},
                        [3] = {"s_inv_thyme01x", 2, 1.4},
                        [4] = {"s_inv_thyme01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_creeping_thyme", 5},
                        [50] = {"crop_creeping_thyme", 3},
                        [25] = {"crop_creeping_thyme", 2},
                        [0] = {"crop_creeping_thyme", 1},
                },
        },
	
        ["seed_desert_sage"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Desert Sage",
                herbItem = "crop_desert_sage",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_desertsage01x", 6, 3.0},
                        [2] = {"s_inv_desertsage01x", 3, 2.2},
                        [3] = {"s_inv_desertsage01x", 2, 1.4},
                        [4] = {"s_inv_desertsage01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_desert_sage", 5},
                        [50] = {"crop_desert_sage", 3},
                        [25] = {"crop_desert_sage", 2},
                        [0] = {"crop_desert_sage", 1},
                },
        },
	
        ["seed_english_mace"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "English Mace",
                herbItem = "crop_english_mace",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_engmace01x", 6, 3.0},
                        [2] = {"s_inv_engmace01x", 3, 2.2},
                        [3] = {"s_inv_engmace01x", 2, 1.4},
                        [4] = {"s_inv_engmace01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_english_mace", 5},
                        [50] = {"crop_english_mace", 3},
                        [25] = {"crop_english_mace", 2},
                        [0] = {"crop_english_mace", 1},
                },
        },
	
        ["seed_evergreen_huckleberry"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Evergreen Huckleberry",
                herbItem = "crop_evergreen_huckleberry",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_huckleberry01x", 6, 3.0},
                        [2] = {"s_inv_huckleberry01x", 3, 2.2},
                        [3] = {"s_inv_huckleberry01x", 2, 1.4},
                        [4] = {"s_inv_huckleberry01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_evergreen_huckleberry", 5},
                        [50] = {"crop_evergreen_huckleberry", 3},
                        [25] = {"crop_evergreen_huckleberry", 2},
                        [0] = {"crop_evergreen_huckleberry", 1},
                },
        },
	
        ["seed_golden_currant"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Golden Currant",
                herbItem = "crop_golden_currant",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_goldencurrant01x", 6, 3.0},
                        [2] = {"s_inv_goldencurrant01x", 3, 2.2},
                        [3] = {"s_inv_goldencurrant01x", 2, 1.4},
                        [4] = {"s_inv_goldencurrant01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_golden_currant", 5},
                        [50] = {"crop_golden_currant", 3},
                        [25] = {"crop_golden_currant", 2},
                        [0] = {"crop_golden_currant", 1},
                },
        },
	
        ["seed_harrietum_officinalis"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Harrietum Officinalis",
                herbItem = "crop_harrietum_officinalis",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"mp007_s_inv_harrietum01x", 6, 3.0},
                        [2] = {"mp007_s_inv_harrietum01x", 3, 2.2},
                        [3] = {"mp007_s_inv_harrietum01x", 2, 1.4},
                        [4] = {"mp007_s_inv_harrietum01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_harrietum_officinalis", 5},
                        [50] = {"crop_harrietum_officinalis", 3},
                        [25] = {"crop_harrietum_officinalis", 2},
                        [0] = {"crop_harrietum_officinalis", 1},
                },
        },
	
        ["seed_hummingbird_sage"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Hummingbird Sage",
                herbItem = "crop_hummingbird_sage",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_humbirdsage01x", 6, 3.0},
                        [2] = {"s_inv_humbirdsage01x", 3, 2.2},
                        [3] = {"s_inv_humbirdsage01x", 2, 1.4},
                        [4] = {"s_inv_humbirdsage01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_hummingbird_sage", 5},
                        [50] = {"crop_hummingbird_sage", 3},
                        [25] = {"crop_hummingbird_sage", 2},
                        [0] = {"crop_hummingbird_sage", 1},
                },
        },
	
        ["seed_milkweed"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Milkweed",
                herbItem = "crop_milkweed",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_milkweed01x", 6, 3.0},
                        [2] = {"s_inv_milkweed01x", 3, 2.2},
                        [3] = {"s_inv_milkweed01x", 2, 1.4},
                        [4] = {"s_inv_milkweed01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_milkweed", 5},
                        [50] = {"crop_milkweed", 3},
                        [25] = {"crop_milkweed", 2},
                        [0] = {"crop_milkweed", 1},
                },
        },
	
        ["seed_orleander_sage"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Oleander Sage",
                herbItem = "crop_orleander_sage",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_orleander01x", 6, 3.0},
                        [2] = {"s_inv_orleander01x", 3, 2.2},
                        [3] = {"s_inv_orleander01x", 2, 1.4},
                        [4] = {"s_inv_orleander01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_orleander_sage", 5},
                        [50] = {"crop_orleander_sage", 3},
                        [25] = {"crop_orleander_sage", 2},
                        [0] = {"crop_orleander_sage", 1},
                },
        },
	
        ["seed_oregano"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Oregano",
                herbItem = "crop_oregano",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_oregano01x", 6, 3.0},
                        [2] = {"s_inv_oregano01x", 3, 2.2},
                        [3] = {"s_inv_oregano01x", 2, 1.4},
                        [4] = {"s_inv_oregano01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_oregano", 5},
                        [50] = {"crop_oregano", 3},
                        [25] = {"crop_oregano", 2},
                        [0] = {"crop_oregano", 1},
                },
        },
	
        ["seed_parasol_mushroom"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Parasol Mushroom",
                herbItem = "crop_parasol_mushroom",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_oregano01x", 6, 3.0},
                        [2] = {"s_inv_oregano01x", 3, 2.2},
                        [3] = {"s_inv_oregano01x", 2, 1.4},
                        [4] = {"s_inv_oregano01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_parasol_mushroom", 5},
                        [50] = {"crop_parasol_mushroom", 3},
                        [25] = {"crop_parasol_mushroom", 2},
                        [0] = {"crop_parasol_mushroom", 1},
                },
        },
	
        ["seed_prarie_poppy"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Prairie Poppy",
                herbItem = "crop_prarie_poppy",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_prariepoppy01x", 6, 3.0},
                        [2] = {"s_inv_prariepoppy01x", 3, 2.2},
                        [3] = {"s_inv_prariepoppy01x", 2, 1.4},
                        [4] = {"s_inv_prariepoppy01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_prarie_poppy", 5},
                        [50] = {"crop_prarie_poppy", 3},
                        [25] = {"crop_prarie_poppy", 2},
                        [0] = {"crop_prarie_poppy", 1},
                },
        },
	
        ["seed_rams_head"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Ram's Head",
                herbItem = "crop_rams_head",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_ramshead01bx", 6, 3.0},
                        [2] = {"s_inv_ramshead01bx", 3, 2.2},
                        [3] = {"s_inv_ramshead01bx", 2, 1.4},
                        [4] = {"s_inv_ramshead01bx", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_rams_head", 5},
                        [50] = {"crop_rams_head", 3},
                        [25] = {"crop_rams_head", 2},
                        [0] = {"crop_rams_head", 1},
                },
        },
	
        ["seed_red_raspberry"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Red Raspberry",
                herbItem = "crop_red_raspberry",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_raspberry01x", 6, 3.0},
                        [2] = {"s_inv_raspberry01x", 3, 2.2},
                        [3] = {"s_inv_raspberry01x", 2, 1.4},
                        [4] = {"s_inv_raspberry01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_red_raspberry", 5},
                        [50] = {"crop_red_raspberry", 3},
                        [25] = {"crop_red_raspberry", 2},
                        [0] = {"crop_red_raspberry", 1},
                },
        },
	
        ["seed_red_sage"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Red Sage",
                herbItem = "crop_red_sage",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_redsage01x", 6, 3.0},
                        [2] = {"s_inv_redsage01x", 3, 2.2},
                        [3] = {"s_inv_redsage01x", 2, 1.4},
                        [4] = {"s_inv_redsage01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_red_sage", 5},
                        [50] = {"crop_red_sage", 3},
                        [25] = {"crop_red_sage", 2},
                        [0] = {"crop_red_sage", 1},
                },
        },
	
        ["seed_violet_snowdrop"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Violet Snowdrop",
                herbItem = "crop_violet_snowdrop",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_viosnwdrp01x", 6, 3.0},
                        [2] = {"s_inv_viosnwdrp01x", 3, 2.2},
                        [3] = {"s_inv_viosnwdrp01x", 2, 1.4},
                        [4] = {"s_inv_viosnwdrp01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_violet_snowdrop", 5},
                        [50] = {"crop_violet_snowdrop", 3},
                        [25] = {"crop_violet_snowdrop", 2},
                        [0] = {"crop_violet_snowdrop", 1},
                },
        },
	
        ["seed_feverfew"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Feverfew",
                herbItem = "crop_feverfew",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_feverfew01x", 6, 3.0},
                        [2] = {"s_inv_feverfew01x", 3, 2.2},
                        [3] = {"s_inv_feverfew01x", 2, 1.4},
                        [4] = {"s_inv_feverfew01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_feverfew", 5},
                        [50] = {"crop_feverfew", 3},
                        [25] = {"crop_feverfew", 2},
                        [0] = {"crop_feverfew", 1},
                },
        },
	
        ["seed_mint"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Mint",
                herbItem = "crop_mint",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_wildmint01x", 6, 3.0},
                        [2] = {"s_inv_wildmint01x", 3, 2.2},
                        [3] = {"s_inv_wildmint01x", 2, 1.4},
                        [4] = {"s_inv_wildmint01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_mint", 5},
                        [50] = {"crop_mint", 3},
                        [25] = {"crop_mint", 2},
                        [0] = {"crop_mint", 1},
                },
        },
	
        ["seed_wintergreen_berry"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Wintergreen Berry",
                herbItem = "crop_wintergreen_berry",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_wintergreen01x", 6, 3.0},
                        [2] = {"s_inv_wintergreen01x", 3, 2.2},
                        [3] = {"s_inv_wintergreen01x", 2, 1.4},
                        [4] = {"s_inv_wintergreen01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_wintergreen_berry", 5},
                        [50] = {"crop_wintergreen_berry", 3},
                        [25] = {"crop_wintergreen_berry", 2},
                        [0] = {"crop_wintergreen_berry", 1},
                },
        },
	
        ["seed_yarrow"] = {
                enableHerbToSeed = false,
                multipleUse = false,
                multipleEvent = "gum_farming:useSeed",
                herbToSeed = 3,
                herbName = "Yarrow",
                herbItem = "crop_yarrow",
                itIsTree = false,
                canPickAfterGrow = 0,
                potStageProps = {
                        [1] = {"s_inv_yarrow01x", 6, 3.0},
                        [2] = {"s_inv_yarrow01x", 3, 2.2},
                        [3] = {"s_inv_yarrow01x", 2, 1.4},
                        [4] = {"s_inv_yarrow01x", 1, 0.8},
                },
                weatherAffect = true,
                growTime = 30,
                temperatureSlow = -3,
                temperatureGood = {-3, 30},
                temperatureHot = 30,

                fertilizer = 0,
                quality = 100,
                procure = 100,
                jerks = 0,

                gatherAnimation = {"mech_pickup@plant@orchid_plant","base", 5},
                rewardItem = {
                        [80] = {"crop_yarrow", 5},
                        [50] = {"crop_yarrow", 3},
                        [25] = {"crop_yarrow", 2},
                        [0] = {"crop_yarrow", 1},
                },
        },        
}
