Config = {}

Config.PromptKey = 0xB2F377E8         	-- F // Check docs.landminentester.de for more information about prompt keys
Config.PromptRange = 2.0				-- This is the range of the prompt

Config.ReceiveNotification = true		-- This sets if the player will get a notification when he gets a telegram and is online
Config.UseIndicator = true
Config.IndicatorPosition = "bottom-right" -- Possible values: "top-right", "top-left", "bottom-right", "bottom-left"

-- Added 11.06.2025
Config.DisableCompanyNotification = false -- This sets if the company notification will be disabled, if true then the company will not get a notification when a telegram is sent to them
--

Config.Debug = true
Config.useAddressbookItem = false     -- This sets if the address book is used, if true then you need the book to see the adressbook tab.
--The book itself doesnt hold any data its just the requirement to see the adressbook.
Config.addressbookItem = "adressbook" -- This is the item that will be used to check for
Config.changeNumberCommand = "changeNumber" -- This is the command that will be used to change the number of a player

Config.UseCitys = false               -- This sets if the telegrams stations are seperate or every station got the same messages

--Citylabel and and company number are not allowed to be the same
Config.CompanyNumbers = {
	["sdwoodworker"] = { number = "SDWOOD", grade = 2 }, -- This is an example of how to add a company number to a job
	["gov"] = { number = "GOV", grade = 1 }, -- This is an example of how to add a company number to a job
}

--Reserve Number spaces for players to set manual numbers
Config.ReservedNumbers = {
	{ startRange = 0, endRange = 100 },
	{ startRange = 150, endRange = 600 },
}

Config.UseRandomNumbers = false -- Instead of giving numbers in order like 1,2,3 generate a random number between the range
Config.RandomNumberRange = {
	startRange = 600,
	endRange = 1000,
}

-- Here you can write cityLabels and their costs
Config.TelegramCost = {
	["DEFAULT"] = 1,
	["SD"] = 2,
	["VA"] = 1,
}

Config.CityLabels = { "SD", "VA", "AN", "RH", "SB", "BW", "AR", "TW", "EM", "VH" } -- This is the list of city labels that will be used for the telegrams stations                                                      -- This is the cost of the telegram
Config.telegramPaperItem =
"telegram"                                                                         -- This is the item that will be used for the telegram paper
Config.paperItem =
"paper"                                                                            -- This is the item that will be used for the paper

Config.AutomaticProps = { -- Add props that get Auto generated by the script
	["p_mailbox01x"] = {
		prop = "p_mailbox01x",
		cityLabel = "SD",
		label = "Mailbox",
	},
}




Config.TelegramStations = {
	{
		label = "Law Telegram",                          -- This is the label of the telegram station
		cityLabel = "VA",                                -- This is the city label of the telegram station
		jobLock = {
			{ job = "Valentine", grade = 0 },                  -- This is an example of how to add a job to the job lock                 -- This is an example of how to add a job to the job lock
			{ job = "Blackwater", grade = 0 },
			{ job = "Rhodes", grade = 0 },
			{ job = "SaintDenis", grade = 0 },
			{ job = "Armadillo", grade = 0 },
			{ job = "Tumbleweed", grade = 0 },
			{ job = "Annesburg", grade = 0 },
			{ job = "Sisika", grade = 0 },

		},
		checkerStation = true,
		coords = { 2602.69, -1307.13, 52.27, 195.8145 }, -- This is the coords of the telegram station
		npc = {                                          --Optional NPC for the telegram station
			model = "re_kidnappedvictim_females_01",
			displayRange = 25.0,
			x = -177.8109,
			y = 628.6130,
			z = 113.0896,
			h = 148.5947,
		},
		object = {                                                               --Spawn object at the station
			model = "p_mailbox01x",                                              -- Model of the object
			coords = vector3(-190.56060791015625, 631.3736572265625, 112.69080352783203), -- Location of the object
			rotation = vector3(0, 0, 52.17405319213867),                         -- Rotation of the object
			range = 5.0,
		},
		blipSettings = {
			name = "DOJ Telegram",
			sprite = "blip_ambient_tithing",
			color = "PINKISH"
		}
	},
	{
		label = "Saint Denis Telegram Station",
		cityLabel = "SD",
		jobLock = false,
		coords = { 2731.5298, -1402.3912, 46.1331, 212.5984 },
		blipSettings = {
			name = "Saint Denis Telegram",
			sprite = "blip_ambient_tithing",
			color = "PINKISH"
		}
	},
	{
		label = "Emerald Telegram Station",
		cityLabel = "EM",
		jobLock = false,
		coords = { 1522.0232, 439.5628, 90.6307, 7.0644 },
        blipSettings = {
			name = "Emerald Telegram Station",
			sprite = "blip_ambient_tithing",
			color = "PINKISH"
		}
	},
	{
		label = "Annesburg Telegram Station",
		cityLabel = "AN",
		jobLock = false,
		coords = { 2939.5635, 1288.5471, 44.6028, 156.2168 }
	},
	{
		label = "Valentine Telegram Station",
		cityLabel = "VA",
		jobLock = false,
		coords = { -178.7319, 626.5564, 114.0396, 327.0764 }
	},
	{
		label = "Rhodes Telegram Station",
		cityLabel = "RH",
		jobLock = false,
		coords = { 1225.3855, -1294.0931, 76.8592, 229.7048 }
	},
	{
		label = "Armadillo Telegram Station",
		cityLabel = "AR",
		jobLock = false,
		coords = { -3729.0464, -2602.9436, -12.9877, 2.4934 }
	},
	{
		label = "Tumbleweed Telegram Station",
		cityLabel = "TW",
		jobLock = false,
		coords = { -5533.4243, -2951.3579, -0.7328, 0.3415 }
	},
	{
		label = "Blackwater Telegram Station",
		cityLabel = "BW",
		jobLock = false,
		coords = { -875.0049, -1328.7344, 43.9080, 4.5289 }
	},
	{
		label = "Strawberry Telegram Station",
		cityLabel = "SB",
		jobLock = false,
		coords = { -1765.0322, -384.2863, 157.6920, 231.4073 }
	},
	{
		label = "van Horn Telegram Station",
		cityLabel = "VH",
		jobLock = false,
		coords = { 2985.9883, 568.5570, 44.6279, 345.4350 }
	},
	{
		label = "Gouvernment Telegram Station",
		cityLabel = "SD",
		jobLock = {
			{ job = "gov",    grade = 1 },
			{ job = "makler", grade = 1 },
		},
		coords = { 2358.0686, -1164.2098, 47.1194, 184.2444 }
	},
	{
		label = "Marshal Telegram Station",
		cityLabel = "SD",

		jobLock = {
			{ job = "marshal", grade = 1 },
			{ job = "gov",     grade = 1 },
		},
		coords = { 2368.2827, -1161.4650, 52.6704, 194.2622 }
	},
}

Config.Language = {
	-- missingNummer = "Bitte gebe ein Sender Nummer an.",
	-- missingReciever = "Bitte gebe ein Empfänger Nummer an.",
	-- missingCity = "Es wurde kein Empfängerstadt angegeben.",
	-- missingTitle = "Der Title darf nicht leer sein",
	-- missingMessage = "Bitte gebe eine Nachricht an",
	-- notEnoughMoney = "Du hast nicht genug Geld um das Telegram zu versenden",

	-- openPrompt = "Öffnen",
	-- sendTelegram = "Das Telegram wurde verschickt für 0.25$",
	-- telegramPaper = "Das Papier ist leer",
	-- createPaper = "Abschrift erstellt",

	-- changeNumberDescription = "Ändere die Telegram Nummer eines Spielers",
	-- sourceHelp = "Die Quelle des Spielers",
	-- telegramNumberHelp = "Die neue Telegram Nummer",
	-- changeNumberError = "Bitte gebe eine gültige Nummer ein um das Postfach von einem Spieler zu überprüfen",
	-- changeNumberLabel = "Bitte gebe die Nummer ein",

	-- changeCompanyNumberLabel = "Bitte gebe eine Firma ein um die Postfächer von dieser Firma zu überprüfen",

	-- changeCityLabel = "Bitte gebe eine Stadt ein um die Postfächer von dieser Stadt zu überprüfen",


	missingNummer = "Please enter a sender number.",
	missingReciever = "Please enter a receiver number.",
	missingCity = "No receiver city was specified.",
	missingTitle = "The title cannot be empty",
	missingMessage = "Please enter a message",
	notEnoughMoney = "You don't have enough money to send the telegram",

	openPrompt = "Open",
	sendTelegram = "The telegram was sent for",
	telegramPaper = "The paper is empty",
	createPaper = "Transcript created",

	changeNumberDescription = "Change the telegram number of a player",
	sourceHelp = "The source of the player",
	telegramNumberHelp = "The new telegram number",

	changeNumberError = "Please enter a valid number",
	changeNumberLabel = "Please enter a number of a player to check the telegrams",

	changeCompanyNumberLabel = "Please enter a company number to check the telegrams",

	changeCityLabel = "Please enter a city label to check the telegrams",

	receivedTelegram = "You got a telegram",
	
	--Added 11.06.2025
	receivedCompanyTelegram = "Your company received a telegram",
}
