-- ['Weapon label'] = {
--     hashname = 'Weapon name',
--     amount = (number), -- Quantity of the item that will be purchased from the shop
--     money = (number or false),
--     gold = (number or false),
--     rol = (number or false),
--     exp = (number or false),
--     locations = { (Id of the locations or 'all') },
--     CustomComps = (json.decode('Text copied from the comps column of the database') or false),
--     CustomLabel = ('Custom weapon name' or false),
--     CustomDesc = ('Custom weapon description' or false),
-- },

-- ['Item label'] = { 
--     item = (Name of the item to buy),
--     amount = (number), -- Quantity of the item that will be purchased from the shop
--     money = (number or false),
--     gold = (number or false),
--     rol = (number or false),
--     object = (Name of the object that will appear in the store),
--     exp = (number or false),
--     locations = { (Id of the locations or 'all') },
-- },

-- NOTE: If you add 1 'all' location the product will be in all locations.

ConfigStore = {
    [_U('Weapons')] = {
        [_U('Melee')] = {
            [_U('TraddersKnife')] = {
                hashname = 'WEAPON_MELEE_KNIFE_TRADER',
                amount = 1,
                money = 5,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'Rhodes', 'Valentine', 'Annesburg' },
            },
            [_U('Knife')] = {
                hashname = 'WEAPON_MELEE_KNIFE',
                amount = 1,
                money = 5,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('RusticKnife')] = {
                hashname = 'WEAPON_MELEE_KNIFE_RUSTIC',
                amount = 1,
                money = 2,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('JawBoneKnife')] = {
                hashname = 'WEAPON_MELEE_KNIFE_JAWBONE',
                amount = 1,
                money = 2,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('Cleaver')] = {
                hashname = 'WEAPON_MELEE_CLEAVER',
                amount = 1,
                money = 2,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('Hatchet')] = {
                hashname = 'WEAPON_MELEE_HATCHET',
                amount = 1,
                money = 8,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('HunterHatchet')] = {
                hashname = 'WEAPON_MELEE_HATCHET_HUNTER',
                amount = 1,
                money = 8,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('Machete')] = {
                hashname = 'WEAPON_MELEE_MACHETE',
                amount = 1,
                money = 5.5,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('CollectorMachete')] = {
                hashname = 'WEAPON_MELEE_MACHETE_COLLECTOR',
                amount = 1,
                money = 5.5,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('KnifeHorror')] = {
                hashname = 'WEAPON_MELEE_KNIFE_HORROR',
                amount = 1,
                money = 4.5,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('Hammer')] = {
                hashname = 'WEAPON_MELEE_HAMMER',
                amount = 1,
                money = 3.5,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('Torch')] = {
                hashname = 'WEAPON_MELEE_TORCH',
                amount = 1,
                money = 2.5,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('MetalDetector')] = {
                hashname = 'WEAPON_KIT_METAL_DETECTOR',
                amount = 1,
                money = 3,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
        },
        [_U('Bows')] = {
            [_U('Bow')] = {	hashname = 'WEAPON_BOW',
                amount = 1,
                money = 10.75,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('ImprovedBow')] = {
                hashname = 'WEAPON_BOW_IMPROVED',
                amount = 1,
                money = 15,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
        },
        [_U('Rifles')] = {
            [_U('ElephantRifle')] = {
                hashname = 'WEAPON_RIFLE_ELEPHANT',
                amount = 1,
                money = 400,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('VarmintRifle')] = {
                hashname = 'WEAPON_RIFLE_VARMINT',
                amount = 1,
                money = 30.75,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('RollingblockRifle')] = {
                hashname = 'WEAPON_SNIPERRIFLE_ROLLINGBLOCK',
                amount = 1,
                money = 1000,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('CarcanoRifle')] = {
                hashname = 'WEAPON_SNIPERRIFLE_CARCANO',
                amount = 1,
                money = 1000,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('SpringfieldRifle')] = {
                hashname = 'WEAPON_RIFLE_SPRINGFIELD',
                amount = 1,
                money = 1000,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('BoltactionRifle')] = {
                hashname = 'WEAPON_RIFLE_BOLTACTION',
                amount = 1,
                money = 250,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
        },
        [_U('Repeaters')] = {
            [_U('WinchesterRepeater')] = {
                hashname = 'WEAPON_REPEATER_WINCHESTER',
                amount = 1,
                money = 70,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('HenryRepeater')] = {
                hashname = 'WEAPON_REPEATER_HENRY',
                amount = 1,
                money = 75.5,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('EvansRepeater')] = {
                hashname = 'WEAPON_REPEATER_EVANS',
                amount = 1,
                money = 80,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('CarbineRepeater')] = {
                hashname = 'WEAPON_REPEATER_CARBINE',
                amount = 1,
                money = 50,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
        },
        [_U('Pistols')] = {
            [_U('Volcanic')] = {
                hashname = 'WEAPON_PISTOL_VOLCANIC',
                amount = 1,
                money = 1000,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('M1899')] = {
                hashname = 'WEAPON_PISTOL_M1899',
                amount = 1,
                money = 10000,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('SemiAuto')] = {
                hashname = 'WEAPON_PISTOL_SEMIAUTO',
                amount = 1,
                money = 1000,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('Mauser')] = {
                hashname = 'WEAPON_PISTOL_MAUSER',
                amount = 1,
                money = 1000,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
        },
        [_U('Revolvers')] = {
            [_U('Schofield')] = {
                hashname = 'WEAPON_REVOLVER_SCHOFIELD',
                amount = 1,
                money = 50,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('Lemat')] = {
                hashname = 'WEAPON_REVOLVER_LEMAT',
                amount = 1,
                money = 40,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('DoubleAction')] = {
                hashname = 'WEAPON_REVOLVER_DOUBLEACTION',
                amount = 1,
                money = 55,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('DoubleActionGambler')] = {
                hashname = 'WEAPON_REVOLVER_DOUBLEACTION_GAMBLER',
                amount = 1,
                money = 60,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('Cattleman')] = {
                hashname = 'WEAPON_REVOLVER_CATTLEMAN',
                amount = 1,
                money = 25,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('CattlemanMexican')] = {
                hashname = 'WEAPON_REVOLVER_CATTLEMAN_MEXICAN',
                amount = 1,
                money = 25,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('Navy')] = {
                hashname = 'WEAPON_REVOLVER_NAVY',
                amount = 1,
                money = 60,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('NavyCrossover')] = {
                hashname = 'WEAPON_REVOLVER_NAVY_CROSSOVER',
                amount = 1,
                money = 60,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
        },
        [_U('Throwable')] = {
            [_U('Tomahawk')] = {
                hashname = 'WEAPON_THROWN_TOMAHAWK',
                amount = 1,
                money = 10,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('Knives')] = {
                hashname = 'WEAPON_THROWN_THROWING_KNIVES',
                amount = 1,
                money = 8,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('PoisonBottle')] = {
                hashname = 'WEAPON_THROWN_POISONBOTTLE',
                amount = 1,
                money = 15,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('Bolas')] = {
                hashname = 'WEAPON_THROWN_BOLAS',
                amount = 1,
                money = 4,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('BolasHawkmoth')] = {
                hashname = 'WEAPON_THROWN_BOLAS_HAWKMOTH',
                amount = 1,
                money = 4,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('BolasIronspiked')] = {
                hashname = 'WEAPON_THROWN_BOLAS_IRONSPIKED',
                amount = 1,
                money = 4,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('BolasIntertwined')] = {
                hashname = 'WEAPON_THROWN_BOLAS_INTERTWINED',
                amount = 1,
                money = 4,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('Dynamite')] = {
                hashname = 'WEAPON_THROWN_DYNAMITE',
                amount = 1,
                money = 100,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('Molotov')] = {
                hashname = 'WEAPON_THROWN_MOLOTOV',
                amount = 1,
                money = 100,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('MoonshineJug')] = {
                hashname = 'WEAPON_MOONSHINEJUG_MP',
                amount = 1,
                money = 100,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
        },
        [_U('Shotguns')] = {
            [_U('Semiauto')] = {
                hashname = 'WEAPON_SHOTGUN_SEMIAUTO',
                amount = 1,
                money = 100,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('Sawedoff')] = {
                hashname = 'WEAPON_SHOTGUN_SAWEDOFF',
                amount = 1,
                money = 250,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('Repeating')] = {
                hashname = 'WEAPON_SHOTGUN_REPEATING',
                amount = 1,
                money = 1000,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('Pump')] = {
                hashname = 'WEAPON_SHOTGUN_PUMP',
                amount = 1,
                money = 1000,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('Doublebarrel')] = {
                hashname = 'WEAPON_SHOTGUN_DOUBLEBARREL',
                amount = 1,
                money = 500,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('DoublebarrelExotic')] = {
                hashname = 'WEAPON_SHOTGUN_DOUBLEBARREL_EXOTIC',
                amount = 1,
                money = 500,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            
        },
        [_U('Misc')] = {
            [_U('Lasso')] = {
                hashname = 'WEAPON_LASSO',
                amount = 1,
                money = 2,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('ReinforcedLasso')] = {
                hashname = 'WEAPON_LASSO_REINFORCED',
                amount = 1,
                money = 10,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('ImprovedBinoculars')] = {
                hashname = 'WEAPON_KIT_BINOCULARS_IMPROVED',
                amount = 1,
                money = 10,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('Binoculars')] = {
                hashname = 'WEAPON_kIT_BINOCULARS',
                amount = 1,
                money = 5,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('FishingRod')] = {
                hashname = 'WEAPON_FISHINGROD',
                amount = 1,
                money = 3,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('Camera')] = {
                hashname = 'WEAPON_KIT_CAMERA',
                amount = 1,
                money = 40,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('AdvancedCamera')] = {
                hashname = 'WEAPON_kIT_CAMERA_ADVANCED',
                amount = 1,
                money = 200,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('Lantern')] = {
                hashname = 'WEAPON_MELEE_LANTERN',
                amount = 1,
                money = 9.75,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('DavyLantern')] = {
                hashname = 'WEAPON_MELEE_DAVY_LANTERN',
                amount = 1,
                money = 15,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
            [_U('LanternHalloween')] = {
                hashname = 'WEAPON_MELEE_LANTERN_HALLOWEEN',
                amount = 1,
                money = 5.5,
                gold = false,
                rol= false,
                exp = 0,
                locations = { 'all' },
            },
        },
    },
    [_U('Ammo')] = {
        [_U('RepeaterAmmo')] = {
            [_U('RepeaterAmmoNormal')] = {
                item = 'ammorepeaternormal',
                amount = 1,
                money = 1,
                gold = false,
                rol= false,
                exp = 0,
                object = 's_inv_xpres_revammo01x',
                locations = { 'all' },
            },
            [_U('RepeaterAmmoExpress')] = {
                item = 'ammorepeaterexpress',
                amount = 1,
                money = 2,
                gold = false,
                rol= false,
                exp = 0,
                object = 's_inv_xpres_revammo01x',
                locations = { 'all' },
            },
            [_U('RepeaterAmmoExplosive')] = {
                item = 'ammorepeaterexplosive',
                amount = 1,
                money = 5,
                gold = false,
                rol= false,
                exp = 0,
                object = 's_inv_xpres_revammo01x',
                locations = { 'all' },
            },
            [_U('RepeaterAmmoVelocity')] = {
                item = 'ammorepeatervelocity',
                amount = 1,
                money = 5,
                gold = false,
                rol= false,
                exp = 0,
                object = 's_inv_xpres_revammo01x',
                locations = { 'all' },
            },
            [_U('RepeaterAmmoSplitpoint')] = {
                item = 'ammorepeatersplitpoint',
                amount = 1,
                money = 8,
                gold = false,
                rol= false,
                exp = 0,
                object = 's_inv_xpres_revammo01x',
                locations = { 'all' },
            },
        },

        [_U('RevolverAmmo')] = {
            [_U('RevolverAmmoNormal')] = {
                item = 'ammorevolvernormal',
                amount = 1,
                money = 1,
                gold = false,
                rol= false,
                exp = 0,
                object = 'p_ammoboxhalf01x',
                locations = { 'all' },
            },
            [_U('RevolverAmmoExpress')] = {
                item = 'ammorevolverexpress',
                amount = 1,
                money = 2,
                gold = false,
                rol= false,
                exp = 0,
                object = 'p_ammoboxhalf01x',
                locations = { 'all' },
            },
            [_U('RevolverAmmoExplosive')] = {
                item = 'ammorevolverexplosive',
                amount = 1,
                money = 5,
                gold = false,
                rol= false,
                exp = 0,
                object = 'p_ammoboxhalf01x',
                locations = { 'all' },
            },
            [_U('RevolverAmmoVelocity')] = {
                item = 'ammorevolvervelocity',
                amount = 1,
                money = 5,
                gold = false,
                rol= false,
                exp = 0,
                object = 'p_ammoboxhalf01x',
                locations = { 'all' },
            },
            [_U('RevolverAmmoSplitpoint')] = {
                item = 'ammorevolversplitpoint',
                amount = 1,
                money = 8,
                gold = false,
                rol= false,
                exp = 0,
                object = 'p_ammoboxhalf01x',
                locations = { 'all' },
            },
        },
        [_U('RifleAmmo')] = {
            [_U('RifleAmmoNormal')] = {
                item = 'ammoriflenormal',
                amount = 1,
                money = 1,
                gold = false,
                rol= false,
                exp = 0,
                object = 's_inv_repeatxs_rifleammo01x',
                locations = { 'all' },
            },
            [_U('ElephantRifleAmmo')] = {
                item = 'ammoelephant',
                amount = 1,
                money = 10,
                gold = false,
                rol= false,
                exp = 0,
                object = 's_inv_repeatxs_rifleammo01x',
                locations = { 'all' },
            },
            [_U('RifleAmmoExpress')] = {
                item = 'ammorifleexpress',
                amount = 1,
                money = 5,
                gold = false,
                rol= false,
                exp = 0,
                object = 's_inv_repeatxs_rifleammo01x',
                locations = { 'all' },
            },
            [_U('RifleAmmoExplosive')] = {
                item = 'ammorifleexplosive',
                amount = 1,
                money = 5,
                gold = false,
                rol= false,
                exp = 0,
                object = 's_inv_repeatxs_rifleammo01x',
                locations = { 'all' },
            },
            [_U('RifleAmmoVelocity')] = {
                item = 'ammoriflevelocity',
                amount = 1,
                money = 5,
                gold = false,
                rol= false,
                exp = 0,
                object = 's_inv_repeatxs_rifleammo01x',
                locations = { 'all' },
            },
            [_U('RifleAmmoSplitpoint')] = {
                item = 'ammoriflesplitpoint',
                amount = 1,
                money = 8,
                gold = false,
                rol= false,
                exp = 0,
                object = 's_inv_repeatxs_rifleammo01x',
                locations = { 'all' },
            },
        },
        [_U('ShotgunAmmo')] = {
            [_U('ShotgunAmmoIncendiary')] = {
                item = 'ammoshotgunincendiary',
                amount = 1,
                money = 5,
                gold = false,
                rol= false,
                exp = 0,
                object = 's_inv_shotgunammo01x',
                locations = { 'all' },
            },
            [_U('ShotgunAmmoExplosive')] = {
                item = 'ammoshotgunexplosive',
                amount = 1,
                money = 5,
                gold = false,
                rol= false,
                exp = 0,
                object = 's_inv_shotgunammo01x',
                locations = { 'all' },
            },
            [_U('ShotgunAmmoNormal')] = {
                item = 'ammoshotgunnormal',
                amount = 1,
                money = 1,
                gold = false,
                rol= false,
                exp = 0,
                object = 's_inv_shotgunammo01x',
                locations = { 'all' },
            },
            [_U('ShotgunAmmoSlug')] = {
                item = 'ammoshotgunslug',
                amount = 1,
                money = 2,
                gold = false,
                rol= false,
                exp = 0,
                object = 's_inv_shotgunammo01x',
                locations = { 'all' },
            },
        },
        [_U('PistolAmmo')] = {
            [_U('PistolAmmoNormal')] = {
                item = 'ammopistolnormal',
                amount = 1,
                money = 1,
                gold = false,
                rol= false,
                exp = 0,
                object = 's_inv_pistolammo01x',
                locations = { 'all' },
            },
            [_U('PistolAmmoExpress')] = {
                item = 'ammopistolexpress',
                amount = 1,
                money = 2,
                gold = false,
                rol= false,
                exp = 0,
                object = 's_inv_pistolammo01x',
                locations = { 'all' },
            },
            [_U('PistolAmmoExplosive')] = {
                item = 'ammopistolexplosive',
                amount = 1,
                money = 5,
                gold = false,
                rol= false,
                exp = 0,
                object = 's_inv_pistolammo01x',
                locations = { 'all' },
            },
            [_U('PistolAmmoVelocity')] = {
                item = 'ammopistolvelocity',
                amount = 1,
                money = 5,
                gold = false,
                rol= false,
                exp = 0,
                object = 's_inv_pistolammo01x',
                locations = { 'all' },
            },
            [_U('PistolAmmoSplitpoint')] = {
                item = 'ammopistolsplitpoint',
                amount = 1,
                money = 8,
                gold = false,
                rol= false,
                exp = 0,
                object = 's_inv_pistolammo01x',
                locations = { 'all' },
            },
        },
        [_U('ArrowAmmo')] = {
            [_U('ArrowNormal')] = { 
                item = 'ammoarrownormal',
                amount = 1,
                money = 1.5,
                gold = false,
                rol= false,
                exp = 0,
                object = 'p_arrowdisplay02x',
                locations = { 'all' },
            },
            [_U('ArrowFire')] = {
                item = 'ammoarrowfire',
                amount = 1,
                money = 2,
                gold = false,
                rol= false,
                exp = 0,
                object = 'p_arrowdisplay02x',
                locations = { 'all' },
            },
            [_U('ArrowSmallGame')] = {
                item = 'ammoarrowsmallgame',
                amount = 1,
                money = 2.25,
                gold = false,
                rol= false,
                exp = 0,
                object = 'p_arrowdisplay02x',
                locations = { 'all' },
            },
            [_U('ArrowPoison')] = {
                item = 'ammoarrowpoison',
                amount = 1,
                money = 5,
                gold = false,
                rol= false,
                exp = 0,
                object = 'p_arrowdisplay02x',
                locations = { 'all' },
            },
            [_U('ArrowDynamite')] = {
                item = 'ammoarrowdynamite',
                amount = 1,
                money = 5,
                gold = false,
                rol= false,
                exp = 0,
                object = 'p_arrowdisplay02x',
                locations = { 'all' },
            },
        },
        [_U('VarmintAmmo')] = {
            [_U('VarmintAmmo')] = {
                item = 'ammovarmint',
                amount = 1,
                money = 1,
                gold = false,
                rol= false,
                exp = 0,
                object = 's_inv_rifleammo01x',
                locations = { 'all' },
            },
            [_U('VarmintTranquilizerAmmo')] = {
                item = 'ammovarminttranq',
                amount = 1,
                money = 5,
                gold = false,
                rol= false,
                exp = 0,
                object = 's_inv_rifleammo01x',
                locations = { 'all' },
            },
                
        },
        [_U('ThrowingAmmo')] = {
            [_U('KnivesAmmo')] = {
                item = 'ammoknives',
                amount = 1,
                money = 2,
                gold = false,
                rol= false,
                exp = 0,
                object = 'p_knivesbundle02p',
                locations = { 'all' },
            },
            [_U('TomahawkAmmo')] = {
                item = 'ammotomahawk',
                amount = 1,
                money = 2,
                gold = false,
                rol= false,
                exp = 0,
                object = 'w_melee_tomahawk01',
                locations = { 'all' },
            },
            [_U('HatchetAmmo')] = {
                item = 'ammohatchet',
                amount = 1,
                money = 2,
                gold = false,
                rol= false,
                exp = 0,
                object = 'w_melee_hatchet01',
                locations = { 'all' },
            },
            [_U('HatchetCleaverAmmo')] = {
                item = 'ammohatchetcleaver',
                amount = 1,
                money = 2,
                gold = false,
                rol= false,
                exp = 0,
                object = 'w_melee_hatchet02',
                locations = { 'all' },
            },
            [_U('HatchetHunterAmmo')] = {
                item = 'ammohatchethunter',
                amount = 1,
                money = 2,
                gold = false,
                rol= false,
                exp = 0,
                object = 'w_melee_hatchet07',
                locations = { 'all' },
            },
            [_U('PoisonBottleAmmo')] = {
                item = 'ammopoisonbottle',
                amount = 1,
                money = 5,
                gold = false,
                rol= false,
                exp = 0,
                object = 'p_molotovempty01x',
                locations = { 'all' },
            },
                
            [_U('BolasAmmo')] = {
                item = 'ammobola',
                amount = 1,
                money = 1,
                gold = false,
                rol= false,
                exp = 0,
                object = 'p_cs_ropelegsplit',
                locations = { 'all' },
            },
            [_U('BolasHawkmothAmmo')] = {
                item = 'ammobolahawk',
                amount = 1,
                money = 1,
                gold = false,
                rol= false,
                exp = 0,
                object = 'p_cs_ropelegsplit',
                locations = { 'all' },
            },
            [_U('BolasIronspikedAmmo')] = {
                item = 'ammobolaironspiked',
                amount = 1,
                money = 1,
                gold = false,
                rol= false,
                exp = 0,
                object = 'p_cs_ropelegsplit',
                locations = { 'all' },
            },
            [_U('BolasIntertwinedAmmo')] = {
                item = 'ammobolaintertwined',
                amount = 1,
                money = 1,
                gold = false,
                rol= false,
                exp = 0,
                object = 'p_cs_ropelegsplit',
                locations = { 'all' },
            },
            [_U('DynamiteAmmo')] = {
                item = 'ammodynamite',
                amount = 1,
                money = 5,
                gold = false,
                rol= false,
                exp = 0,
                object = 'w_throw_dynamite01',
                locations = { 'all' },
            },
                
            [_U('VolatileDynamiteAmmo')] = {
                item = 'ammovoldynamite',
                amount = 1,
                money = 5,
                gold = false,
                rol= false,
                exp = 0,
                object = 'w_throw_dynamite01',
                locations = { 'all' },
            },
            [_U('MolotovAmmo')] = {
                item = 'ammomolotov',
                amount = 1,
                money = 5,
                gold = false,
                rol= false,
                exp = 0,
                object = 'w_throw_molotov01',
                locations = { 'all' },
            },
            [_U('VolatileMolotovAmmo')] = {
                item = 'ammovolmolotov',
                amount = 1,
                money = 5,
                gold = false,
                rol= false,
                exp = 0,
                object = 'w_throw_molotov01',
                locations = { 'all' },
            },
            [_U('MoonshineJug')] = {
                item = 'ammomoonshinejug',
                amount = 1,
                money = 5,
                gold = false,
                rol= false,
                exp = 0,
                object = 'p_jug01x',
                locations = { 'all' },
            },
        },
    },
}